name:                baby-black-and-whites
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/silky/baby-black-and-whites#readme
license:             BSD3
author:              Noon van der Silk
maintainer:          noonsilk@gmail.com
copyright:           2023 Noon van der Silk
category:            Web
extra-source-files:
  - README.md
  - CHANGELOG.md


default-extensions:
  - FlexibleContexts
  - GADTs
  - ImportQualifiedPost
  - NoMonomorphismRestriction
  - TupleSections


dependencies:
  - base >= 4.7 && < 5
  - diagrams
  - diagrams-cairo
  - diagrams-contrib
  - diagrams-lib
  - random


ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints


executables:
  baby-black-and-whites:
    source-dirs:      src
    main:             Main.hs
